### ISSUE TITLE
mask visualization does not always work

### ISSUE THREAD

**Issue by bertsky** [i008/COCO-dataset-explorer#6]
I have COCO datasets for PNGs in RGB colorspace, with segmentation converted from polygons to RLE format prior to starting COCO Explorer.

But on some images, this happens when activating `Draw prediction masks`:
```
ValueError: operands could not be broadcast together with shapes (56179,) (3,)
Traceback:
File "/opt/conda/lib/python3.7/site-packages/streamlit/ScriptRunner.py", line 322, in _run_script
    exec(code, module.__dict__)
File "/cocodemo/coco_explorer.py", line 153, in <module>
    app(args)
File "/cocodemo/coco_explorer.py", line 65, in app
    figsize=(15, 15))
File "/cocodemo/cocoinspector.py", line 172, in visualize_image
    draw_pred_mask=draw_pred_mask)
File "/cocodemo/vis.py", line 60, in vis_image
    img[mask] = img[mask] * 0.5 + color_mask * 0.5
```

What am I doing wrong?

(Also, I can see nothing when activating `Draw ground truth masks`...)

**Comment by bertsky** [comment]
> (56179,) (3,)

This tells me that `img[mask]` got reduced to only 1 axis (len=56179) instead of 3. I guess this can only happen when `coco.annToMask(ann)` returned something 3-dimensional itself. From what I understand, RLE is always 2-d binary though. (And  I am relying on `pycocotools` to generate them...)

**Comment by bertsky** [comment]
Gosh, that was the wood behind the trees. This of course happens because `img` is expected to be already RGB here, not binarized/grayscale.

Care for a PR?

**Comment by i008** [comment]
Hey Robert,

Thanks for looking into this. I'm currently kinda short on time but should
have some next weekend. But if you have anything and you want to
fix/contribute/PR, please go ahead.
